<?php

namespace dorukyy\loginx\Enums;

class Country
{
    public static function data(): array
    {
        return [
            [
                'name' => 'Argentina',
                'name_native' => 'Argentina',
                'phone_code' => '54',
                'code' => 'AR',
                'flag' => '🇦🇷',
            ],
            [
                'name' => 'Armenia',
                'name_native' => 'Հայաստան',
                'phone_code' => '374',
                'code' => 'AM',
                'flag' => '🇦🇲',
            ],
            [
                'name' => 'Australia',
                'name_native' => 'Australia',
                'phone_code' => '61',
                'code' => 'AU',
                'flag' => '🇦🇺',
            ],
            [
                'name' => 'Austria',
                'name_native' => 'Österreich',
                'phone_code' => '43',
                'code' => 'AT',
                'flag' => '🇦🇹',
            ],
            [
                'name' => 'Azerbaijan',
                'name_native' => 'Azərbaycan',
                'phone_code' => '994',
                'code' => 'AZ',
                'flag' => '🇦🇿',
            ],
            [
                'name' => 'Bahamas',
                'name_native' => 'Bahamas',
                'phone_code' => '1-242',
                'code' => 'BS',
                'flag' => '🇧🇸',
            ],
            [
                'name' => 'Bahrain',
                'name_native' => 'البحرين',
                'phone_code' => '973',
                'code' => 'BH',
                'flag' => '🇧🇭',
            ],
            [
                'name' => 'Bangladesh',
                'name_native' => 'বাংলাদেশ',
                'phone_code' => '880',
                'code' => 'BD',
                'flag' => '🇧🇩',
            ],
            [
                'name' => 'Barbados',
                'name_native' => 'Barbados',
                'phone_code' => '1-246',
                'code' => 'BB',
                'flag' => '🇧🇧',
            ],
            [
                'name' => 'Belarus',
                'name_native' => 'Беларусь',
                'phone_code' => '375',
                'code' => 'BY',
                'flag' => '🇧🇾',
            ],
            [
                'name' => 'Belgium',
                'name_native' => 'België',
                'phone_code' => '32',
                'code' => 'BE',
                'flag' => '🇧🇪',
            ],
            [
                'name' => 'Belize',
                'name_native' => 'Belize',
                'phone_code' => '501',
                'code' => 'BZ',
                'flag' => '🇧🇿',
            ],
            [
                'name' => 'Benin',
                'name_native' => 'Bénin',
                'phone_code' => '229',
                'code' => 'BJ',
                'flag' => '🇧🇯',
            ],
            [
                'name' => 'Bhutan',
                'name_native' => 'འབྲུག་ཡུལ་',
                'phone_code' => '975',
                'code' => 'BT',
                'flag' => '🇧🇹',
            ],
            [
                'name' => 'Bolivia',
                'name_native' => 'Bolivia',
                'phone_code' => '591',
                'code' => 'BO',
                'flag' => '🇧🇴',
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'name_native' => 'Bosna i Hercegovina',
                'phone_code' => '387',
                'code' => 'BA',
                'flag' => '🇧🇦',
            ],
            [
                'name' => 'Botswana',
                'name_native' => 'Botswana',
                'phone_code' => '267',
                'code' => 'BW',
                'flag' => '🇧🇼',
            ],
            [
                'name' => 'Brazil',
                'name_native' => 'Brasil',
                'phone_code' => '55',
                'code' => 'BR',
                'flag' => '🇧🇷',
            ],
            [
                'name' => 'Brunei',
                'name_native' => 'Brunei',
                'phone_code' => '673',
                'code' => 'BN',
                'flag' => '🇧🇳',
            ],
            [
                'name' => 'Bulgaria',
                'name_native' => 'България',
                'phone_code' => '359',
                'code' => 'BG',
                'flag' => '🇧🇬',
            ],
            [
                'name' => 'Burkina Faso',
                'name_native' => 'Burkina Faso',
                'phone_code' => '226',
                'code' => 'BF',
                'flag' => '🇧🇫',
            ],
            [
                'name' => 'Burundi',
                'name_native' => 'Burundi',
                'phone_code' => '257',
                'code' => 'BI',
                'flag' => '🇧🇮',
            ],
            [
                'name' => 'Cambodia',
                'name_native' => 'កម្ពុជា',
                'phone_code' => '855',
                'code' => 'KH',
                'flag' => '🇰🇭',
            ],
            [
                'name' => 'Cameroon',
                'name_native' => 'Cameroun',
                'phone_code' => '237',
                'code' => 'CM',
                'flag' => '🇨🇲',
            ],
            [
                'name' => 'Canada',
                'name_native' => 'Canada',
                'phone_code' => '1',
                'code' => 'CA',
                'flag' => '🇨🇦',
            ],
            [
                'name' => 'Cape Verde',
                'name_native' => 'Cabo Verde',
                'phone_code' => '238',
                'code' => 'CV',
                'flag' => '🇨🇻',
            ],
            [
                'name' => 'Central African Republic',
                'name_native' => 'République centrafricaine',
                'phone_code' => '236',
                'code' => 'CF',
                'flag' => '🇨🇫',
            ],
            [
                'name' => 'Chad',
                'name_native' => 'Tchad',
                'phone_code' => '235',
                'code' => 'TD',
                'flag' => '🇹🇩',
            ],
            [
                'name' => 'Chile',
                'name_native' => 'Chile',
                'phone_code' => '56',
                'code' => 'CL',
                'flag' => '🇨🇱',
            ],
            [
                'name' => 'China',
                'name_native' => '中国',
                'phone_code' => '86',
                'code' => 'CN',
                'flag' => '🇨🇳',
            ],
            [
                'name' => 'Colombia',
                'name_native' => 'Colombia',
                'phone_code' => '57',
                'code' => 'CO',
                'flag' => '🇨🇴',
            ],
            [
                'name' => 'Comoros',
                'name_native' => 'Komori',
                'phone_code' => '269',
                'code' => 'KM',
                'flag' => '🇰🇲',
            ],
            [
                'name' => 'Congo',
                'name_native' => 'Congo',
                'phone_code' => '242',
                'code' => 'CG',
                'flag' => '🇨🇬',
            ],
            [
                'name' => 'Costa Rica',
                'name_native' => 'Costa Rica',
                'phone_code' => '506',
                'code' => 'CR',
                'flag' => '🇨🇷',
            ],
            [
                'name' => 'Croatia',
                'name_native' => 'Hrvatska',
                'phone_code' => '385',
                'code' => 'HR',
                'flag' => '🇭🇷',
            ],
            [
                'name' => 'Cuba',
                'name_native' => 'Cuba',
                'phone_code' => '53',
                'code' => 'CU',
                'flag' => '🇨🇺',
            ],
            [
                'name' => 'Cyprus',
                'name_native' => 'Κύπρος',
                'phone_code' => '357',
                'code' => 'CY',
                'flag' => '🇨🇾',
            ],
            [
                'name' => 'Czech Republic',
                'name_native' => 'Česká republika',
                'phone_code' => '420',
                'code' => 'CZ',
                'flag' => '🇨🇿',
            ],
            [
                'name' => 'Denmark',
                'name_native' => 'Danmark',
                'phone_code' => '45',
                'code' => 'DK',
                'flag' => '🇩🇰',
            ],
            [
                'name' => 'Djibouti',
                'name_native' => 'Djibouti',
                'phone_code' => '253',
                'code' => 'DJ',
                'flag' => '🇩🇯',
            ],
            [
                'name' => 'Dominica',
                'name_native' => 'Dominica',
                'phone_code' => '1-767',
                'code' => 'DM',
                'flag' => '🇩🇲',
            ],
            [
                'name' => 'Dominican Republic',
                'name_native' => 'República Dominicana',
                'phone_code' => '1-809',
                'code' => 'DO',
                'flag' => '🇩🇴',
            ],
            [
                'name' => 'Ecuador',
                'name_native' => 'Ecuador',
                'phone_code' => '593',
                'code' => 'EC',
                'flag' => '🇪🇨',
            ],
            [
                'name' => 'Egypt',
                'name_native' => 'مصر',
                'phone_code' => '20',
                'code' => 'EG',
                'flag' => '🇪🇬',
            ],
            [
                'name' => 'El Salvador',
                'name_native' => 'El Salvador',
                'phone_code' => '503',
                'code' => 'SV',
                'flag' => '🇸🇻',
            ],
            [
                'name' => 'Equatorial Guinea',
                'name_native' => 'Guinea Ecuatorial',
                'phone_code' => '240',
                'code' => 'GQ',
                'flag' => '🇬🇶',
            ],
            [
                'name' => 'Eritrea',
                'name_native' => 'ኤርትራ',
                'phone_code' => '291',
                'code' => 'ER',
                'flag' => '🇪🇷',
            ],
            [
                'name' => 'Estonia',
                'name_native' => 'Eesti',
                'phone_code' => '372',
                'code' => 'EE',
                'flag' => '🇪🇪',
            ],
            [
                'name' => 'Eswatini',
                'name_native' => 'Eswatini',
                'phone_code' => '268',
                'code' => 'SZ',
                'flag' => '🇸🇿',
            ],
            [
                'name' => 'Ethiopia',
                'name_native' => 'ኢትዮጵያ',
                'phone_code' => '251',
                'code' => 'ET',
                'flag' => '🇪🇹',
            ],
            [
                'name' => 'Fiji',
                'name_native' => 'Fiji',
                'phone_code' => '679',
                'code' => 'FJ',
                'flag' => '🇫🇯',
            ],
            [
                'name' => 'Finland',
                'name_native' => 'Suomi',
                'phone_code' => '358',
                'code' => 'FI',
                'flag' => '🇫🇮',
            ],
            [
                'name' => 'France',
                'name_native' => 'France',
                'phone_code' => '33',
                'code' => 'FR',
                'flag' => '🇫🇷',
            ],
            [
                'name' => 'Gabon',
                'name_native' => 'Gabon',
                'phone_code' => '241',
                'code' => 'GA',
                'flag' => '🇬🇦',
            ],
            [
                'name' => 'Gambia',
                'name_native' => 'Gambia',
                'phone_code' => '220',
                'code' => 'GM',
                'flag' => '🇬🇲',
            ],
            [
                'name' => 'Georgia',
                'name_native' => 'საქართველო',
                'phone_code' => '995',
                'code' => 'GE',
                'flag' => '🇬🇪',
            ],
            [
                'name' => 'Germany',
                'name_native' => 'Deutschland',
                'phone_code' => '49',
                'code' => 'DE',
                'flag' => '🇩🇪',
            ],
            [
                'name' => 'Ghana',
                'name_native' => 'Ghana',
                'phone_code' => '233',
                'code' => 'GH',
                'flag' => '🇬🇭',
            ],
            [
                'name' => 'Greece',
                'name_native' => 'Ελλάδα',
                'phone_code' => '30',
                'code' => 'GR',
                'flag' => '🇬🇷',
            ],
            [
                'name' => 'Grenada',
                'name_native' => 'Grenada',
                'phone_code' => '1-473',
                'code' => 'GD',
                'flag' => '🇬🇩',
            ],
            [
                'name' => 'Guatemala',
                'name_native' => 'Guatemala',
                'phone_code' => '502',
                'code' => 'GT',
                'flag' => '🇬🇹',
            ],
            [
                'name' => 'Guinea',
                'name_native' => 'Guinée',
                'phone_code' => '224',
                'code' => 'GN',
                'flag' => '🇬🇳',
            ],
            [
                'name' => 'Guinea-Bissau',
                'name_native' => 'Guiné-Bissau',
                'phone_code' => '245',
                'code' => 'GW',
                'flag' => '🇬🇼',
            ],
            [
                'name' => 'Guyana',
                'name_native' => 'Guyana',
                'phone_code' => '592',
                'code' => 'GY',
                'flag' => '🇬🇾',
            ],
            [
                'name' => 'Haiti',
                'name_native' => 'Haïti',
                'phone_code' => '509',
                'code' => 'HT',
                'flag' => '🇭🇹',
            ],
            [
                'name' => 'Honduras',
                'name_native' => 'Honduras',
                'phone_code' => '504',
                'code' => 'HN',
                'flag' => '🇭🇳',
            ],
            [
                'name' => 'Hungary',
                'name_native' => 'Magyarország',
                'phone_code' => '36',
                'code' => 'HU',
                'flag' => '🇭🇺',
            ],
            [
                'name' => 'Iceland',
                'name_native' => 'Ísland',
                'phone_code' => '354',
                'code' => 'IS',
                'flag' => '🇮🇸',
            ],
            [
                'name' => 'India',
                'name_native' => 'भारत',
                'phone_code' => '91',
                'code' => 'IN',
                'flag' => '🇮🇳',
            ],
            [
                'name' => 'Indonesia',
                'name_native' => 'Indonesia',
                'phone_code' => '62',
                'code' => 'ID',
                'flag' => '🇮🇩',
            ],
            [
                'name' => 'Iran',
                'name_native' => 'ایران',
                'phone_code' => '98',
                'code' => 'IR',
                'flag' => '🇮🇷',
            ],
            [
                'name' => 'Iraq',
                'name_native' => 'العراق',
                'phone_code' => '964',
                'code' => 'IQ',
                'flag' => '🇮🇶',
            ],
            [
                'name' => 'Ireland',
                'name_native' => 'Éire',
                'phone_code' => '353',
                'code' => 'IE',
                'flag' => '🇮🇪',
            ],
            [
                'name' => 'Israel',
                'name_native' => 'יִשְׂרָאֵל',
                'phone_code' => '972',
                'code' => 'IL',
                'flag' => '🇮🇱',
            ],
            [
                'name' => 'Italy',
                'name_native' => 'Italia',
                'phone_code' => '39',
                'code' => 'IT',
                'flag' => '🇮🇹',
            ],
            [
                'name' => 'Jamaica',
                'name_native' => 'Jamaica',
                'phone_code' => '1-876',
                'code' => 'JM',
                'flag' => '🇯🇲',
            ],
            [
                'name' => 'Japan',
                'name_native' => '日本',
                'phone_code' => '81',
                'code' => 'JP',
                'flag' => '🇯🇵',
            ],
            [
                'name' => 'Jordan',
                'name_native' => 'الأردن',
                'phone_code' => '962',
                'code' => 'JO',
                'flag' => '🇯🇴',
            ],
            [
                'name' => 'Kazakhstan',
                'name_native' => 'Қазақстан',
                'phone_code' => '7',
                'code' => 'KZ',
                'flag' => '🇰🇿',
            ],
            [
                'name' => 'Kenya',
                'name_native' => 'Kenya',
                'phone_code' => '254',
                'code' => 'KE',
                'flag' => '🇰🇪',
            ],
            [
                'name' => 'Kiribati',
                'name_native' => 'Kiribati',
                'phone_code' => '686',
                'code' => 'KI',
                'flag' => '🇰🇮',
            ],
            [
                'name' => 'Kuwait',
                'name_native' => 'الكويت',
                'phone_code' => '965',
                'code' => 'KW',
                'flag' => '🇰🇼',
            ],
            [
                'name' => 'Kyrgyzstan',
                'name_native' => 'Кыргызстан',
                'phone_code' => '996',
                'code' => 'KG',
                'flag' => '🇰🇬',
            ],
            [
                'name' => 'Laos',
                'name_native' => 'ລາວ',
                'phone_code' => '856',
                'code' => 'LA',
                'flag' => '🇱🇦',
            ],
            [
                'name' => 'Latvia',
                'name_native' => 'Latvija',
                'phone_code' => '371',
                'code' => 'LV',
                'flag' => '🇱🇻',
            ],
            [
                'name' => 'Lebanon',
                'name_native' => 'لبنان',
                'phone_code' => '961',
                'code' => 'LB',
                'flag' => '🇱🇧',
            ],
            [
                'name' => 'Lesotho',
                'name_native' => 'Lesotho',
                'phone_code' => '266',
                'code' => 'LS',
                'flag' => '🇱🇸',
            ],
            [
                'name' => 'Liberia',
                'name_native' => 'Liberia',
                'phone_code' => '231',
                'code' => 'LR',
                'flag' => '🇱🇷',
            ],
            [
                'name' => 'Libya',
                'name_native' => 'ليبيا',
                'phone_code' => '218',
                'code' => 'LY',
                'flag' => '🇱🇾',
            ],
            [
                'name' => 'Liechtenstein',
                'name_native' => 'Liechtenstein',
                'phone_code' => '423',
                'code' => 'LI',
                'flag' => '🇱🇮',
            ],
            [
                'name' => 'Lithuania',
                'name_native' => 'Lietuva',
                'phone_code' => '370',
                'code' => 'LT',
                'flag' => '🇱🇹',
            ],
            [
                'name' => 'Luxembourg',
                'name_native' => 'Luxembourg',
                'phone_code' => '352',
                'code' => 'LU',
                'flag' => '🇱🇺',
            ],
            [
                'name' => 'Madagascar',
                'name_native' => 'Madagasikara',
                'phone_code' => '261',
                'code' => 'MG',
                'flag' => '🇲🇬',
            ],
            [
                'name' => 'Malawi',
                'name_native' => 'Malawi',
                'phone_code' => '265',
                'code' => 'MW',
                'flag' => '🇲🇼',
            ],
            [
                'name' => 'Malaysia',
                'name_native' => 'Malaysia',
                'phone_code' => '60',
                'code' => 'MY',
                'flag' => '🇲🇾',
            ],
            [
                'name' => 'Maldives',
                'name_native' => 'Maldives',
                'phone_code' => '960',
                'code' => 'MV',
                'flag' => '🇲🇻',
            ],
            [
                'name' => 'Mali',
                'name_native' => 'Mali',
                'phone_code' => '223',
                'code' => 'ML',
                'flag' => '🇲🇱',
            ],
            [
                'name' => 'Malta',
                'name_native' => 'Malta',
                'phone_code' => '356',
                'code' => 'MT',
                'flag' => '🇲🇹',
            ],
            [
                'name' => 'Marshall Islands',
                'name_native' => 'Marshall Islands',
                'phone_code' => '692',
                'code' => 'MH',
                'flag' => '🇲🇭',
            ],
            [
                'name' => 'Mauritania',
                'name_native' => 'موريتانيا',
                'phone_code' => '222',
                'code' => 'MR',
                'flag' => '🇲🇷',
            ],
            [
                'name' => 'Mauritius',
                'name_native' => 'Mauritius',
                'phone_code' => '230',
                'code' => 'MU',
                'flag' => '🇲🇺',
            ],
            [
                'name' => 'Mexico',
                'name_native' => 'México',
                'phone_code' => '52',
                'code' => 'MX',
                'flag' => '🇲🇽',
            ],
            [
                'name' => 'Micronesia',
                'name_native' => 'Micronesia',
                'phone_code' => '691',
                'code' => 'FM',
                'flag' => '🇫🇲',
            ],
            [
                'name' => 'Moldova',
                'name_native' => 'Moldova',
                'phone_code' => '373',
                'code' => 'MD',
                'flag' => '🇲🇩',
            ],
            [
                'name' => 'Monaco',
                'name_native' => 'Monaco',
                'phone_code' => '377',
                'code' => 'MC',
                'flag' => '🇲🇨',
            ],
            [
                'name' => 'Mongolia',
                'name_native' => 'Монгол',
                'phone_code' => '976',
                'code' => 'MN',
                'flag' => '🇲🇳',
            ],
            [
                'name' => 'Montenegro',
                'name_native' => 'Crna Gora',
                'phone_code' => '382',
                'code' => 'ME',
                'flag' => '🇲🇪',
            ],
            [
                'name' => 'Morocco',
                'name_native' => 'المغرب',
                'phone_code' => '212',
                'code' => 'MA',
                'flag' => '🇲🇦',
            ],
            [
                'name' => 'Mozambique',
                'name_native' => 'Moçambique',
                'phone_code' => '258',
                'code' => 'MZ',
                'flag' => '🇲🇿',
            ],
            [
                'name' => 'Myanmar',
                'name_native' => 'မြန်မာ',
                'phone_code' => '95',
                'code' => 'MM',
                'flag' => '🇲🇲',
            ],
            [
                'name' => 'Namibia',
                'name_native' => 'Namibia',
                'phone_code' => '264',
                'code' => 'NA',
                'flag' => '🇳🇦',
            ],
            [
                'name' => 'Nauru',
                'name_native' => 'Nauru',
                'phone_code' => '674',
                'code' => 'NR',
                'flag' => '🇳🇷',
            ],
            [
                'name' => 'Nepal',
                'name_native' => 'नेपाल',
                'phone_code' => '977',
                'code' => 'NP',
                'flag' => '🇳🇵',
            ],
            [
                'name' => 'Netherlands',
                'name_native' => 'Nederland',
                'phone_code' => '31',
                'code' => 'NL',
                'flag' => '🇳🇱',
            ],
            [
                'name' => 'New Zealand',
                'name_native' => 'New Zealand',
                'phone_code' => '64',
                'code' => 'NZ',
                'flag' => '🇳🇿',
            ],
            [
                'name' => 'Nicaragua',
                'name_native' => 'Nicaragua',
                'phone_code' => '505',
                'code' => 'NI',
                'flag' => '🇳🇮',
            ],
            [
                'name' => 'Niger',
                'name_native' => 'Niger',
                'phone_code' => '227',
                'code' => 'NE',
                'flag' => '🇳🇪',
            ],
            [
                'name' => 'Nigeria',
                'name_native' => 'Nigeria',
                'phone_code' => '234',
                'code' => 'NG',
                'flag' => '🇳🇬',
            ],
            [
                'name' => 'North Korea',
                'name_native' => '조선민주주의인민공화국',
                'phone_code' => '850',
                'code' => 'KP',
                'flag' => '🇰🇵',
            ],
            [
                'name' => 'North Macedonia',
                'name_native' => 'Северна Македонија',
                'phone_code' => '389',
                'code' => 'MK',
                'flag' => '🇲🇰',
            ],
            [
                'name' => 'Norway',
                'name_native' => 'Norge',
                'phone_code' => '47',
                'code' => 'NO',
                'flag' => '🇳🇴',
            ],
            [
                'name' => 'Oman',
                'name_native' => 'عمان',
                'phone_code' => '968',
                'code' => 'OM',
                'flag' => '🇴🇲',
            ],
            [
                'name' => 'Pakistan',
                'name_native' => 'پاکستان',
                'phone_code' => '92',
                'code' => 'PK',
                'flag' => '🇵🇰',
            ],
            [
                'name' => 'Palau',
                'name_native' => 'Palau',
                'phone_code' => '680',
                'code' => 'PW',
                'flag' => '🇵🇼',
            ],
            [
                'name' => 'Palestine',
                'name_native' => 'فلسطين',
                'phone_code' => '970',
                'code' => 'PS',
                'flag' => '🇵🇸',
            ],
            [
                'name' => 'Panama',
                'name_native' => 'Panamá',
                'phone_code' => '507',
                'code' => 'PA',
                'flag' => '🇵🇦',
            ],
            [
                'name' => 'Papua New Guinea',
                'name_native' => 'Papua New Guinea',
                'phone_code' => '675',
                'code' => 'PG',
                'flag' => '🇵🇬',
            ],
            [
                'name' => 'Paraguay',
                'name_native' => 'Paraguay',
                'phone_code' => '595',
                'code' => 'PY',
                'flag' => '🇵🇾',
            ],
            [
                'name' => 'Peru',
                'name_native' => 'Perú',
                'phone_code' => '51',
                'code' => 'PE',
                'flag' => '🇵🇪',
            ],
            [
                'name' => 'Philippines',
                'name_native' => 'Pilipinas',
                'phone_code' => '63',
                'code' => 'PH',
                'flag' => '🇵🇭',
            ],
            [
                'name' => 'Poland',
                'name_native' => 'Polska',
                'phone_code' => '48',
                'code' => 'PL',
                'flag' => '🇵🇱',
            ],
            [
                'name' => 'Portugal',
                'name_native' => 'Portugal',
                'phone_code' => '351',
                'code' => 'PT',
                'flag' => '🇵🇹',
            ],
            [
                'name' => 'Qatar',
                'name_native' => 'قطر',
                'phone_code' => '974',
                'code' => 'QA',
                'flag' => '🇶🇦',
            ],
            [
                'name' => 'Romania',
                'name_native' => 'România',
                'phone_code' => '40',
                'code' => 'RO',
                'flag' => '🇷🇴',
            ],
            [
                'name' => 'Russia',
                'name_native' => 'Россия',
                'phone_code' => '7',
                'code' => 'RU',
                'flag' => '🇷🇺',
            ],
            [
                'name' => 'Rwanda',
                'name_native' => 'Rwanda',
                'phone_code' => '250',
                'code' => 'RW',
                'flag' => '🇷🇼',
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'name_native' => 'Saint Kitts and Nevis',
                'phone_code' => '1-869',
                'code' => 'KN',
                'flag' => '🇰🇳',
            ],
            [
                'name' => 'Saint Lucia',
                'name_native' => 'Saint Lucia',
                'phone_code' => '1-758',
                'code' => 'LC',
                'flag' => '🇱🇨',
            ],
            [
                'name' => 'Saint Vincent and the Grenadines',
                'name_native' => 'Saint Vincent and the Grenadines',
                'phone_code' => '1-784',
                'code' => 'VC',
                'flag' => '🇻🇨',
            ],
            [
                'name' => 'Samoa',
                'name_native' => 'Samoa',
                'phone_code' => '685',
                'code' => 'WS',
                'flag' => '🇼🇸',
            ],
            [
                'name' => 'San Marino',
                'name_native' => 'San Marino',
                'phone_code' => '378',
                'code' => 'SM',
                'flag' => '🇸🇲',
            ],
            [
                'name' => 'Sao Tome and Principe',
                'name_native' => 'São Tomé e Príncipe',
                'phone_code' => '239',
                'code' => 'ST',
                'flag' => '🇸🇹',
            ],
            [
                'name' => 'Saudi Arabia',
                'name_native' => 'المملكة العربية السعودية',
                'phone_code' => '966',
                'code' => 'SA',
                'flag' => '🇸🇦',
            ],
            [
                'name' => 'Senegal',
                'name_native' => 'Sénégal',
                'phone_code' => '221',
                'code' => 'SN',
                'flag' => '🇸🇳',
            ],
            [
                'name' => 'Serbia',
                'name_native' => 'Србија',
                'phone_code' => '381',
                'code' => 'RS',
                'flag' => '🇷🇸',
            ],
            [
                'name' => 'Seychelles',
                'name_native' => 'Seychelles',
                'phone_code' => '248',
                'code' => 'SC',
                'flag' => '🇸🇨',
            ],
            [
                'name' => 'Sierra Leone',
                'name_native' => 'Sierra Leone',
                'phone_code' => '232',
                'code' => 'SL',
                'flag' => '🇸🇱',
            ],
            [
                'name' => 'Singapore',
                'name_native' => 'Singapore',
                'phone_code' => '65',
                'code' => 'SG',
                'flag' => '🇸🇬',
            ],
            [
                'name' => 'Slovakia',
                'name_native' => 'Slovensko',
                'phone_code' => '421',
                'code' => 'SK',
                'flag' => '🇸🇰',
            ],
            [
                'name' => 'Slovenia',
                'name_native' => 'Slovenija',
                'phone_code' => '386',
                'code' => 'SI',
                'flag' => '🇸🇮',
            ],
            [
                'name' => 'Solomon Islands',
                'name_native' => 'Solomon Islands',
                'phone_code' => '677',
                'code' => 'SB',
                'flag' => '🇸🇧',
            ],
            [
                'name' => 'Somalia',
                'name_native' => 'Soomaaliya',
                'phone_code' => '252',
                'code' => 'SO',
                'flag' => '🇸🇴',
            ],
            [
                'name' => 'South Africa',
                'name_native' => 'South Africa',
                'phone_code' => '27',
                'code' => 'ZA',
                'flag' => '🇿🇦',
            ],
            [
                'name' => 'South Korea',
                'name_native' => '대한민국',
                'phone_code' => '82',
                'code' => 'KR',
                'flag' => '🇰🇷',
            ],
            [
                'name' => 'South Sudan',
                'name_native' => 'South Sudan',
                'phone_code' => '211',
                'code' => 'SS',
                'flag' => '🇸🇸',
            ],
            [
                'name' => 'Spain',
                'name_native' => 'España',
                'phone_code' => '34',
                'code' => 'ES',
                'flag' => '🇪🇸',
            ],
            [
                'name' => 'Sri Lanka',
                'name_native' => 'ශ්‍රී ලංකාව',
                'phone_code' => '94',
                'code' => 'LK',
                'flag' => '🇱🇰',
            ],
            [
                'name' => 'Sudan',
                'name_native' => 'السودان',
                'phone_code' => '249',
                'code' => 'SD',
                'flag' => '🇸🇩',
            ],
            [
                'name' => 'Suriname',
                'name_native' => 'Suriname',
                'phone_code' => '597',
                'code' => 'SR',
                'flag' => '🇸🇷',
            ],
            [
                'name' => 'Sweden',
                'name_native' => 'Sverige',
                'phone_code' => '46',
                'code' => 'SE',
                'flag' => '🇸🇪',
            ],
            [
                'name' => 'Switzerland',
                'name_native' => 'Schweiz',
                'phone_code' => '41',
                'code' => 'CH',
                'flag' => '🇨🇭',
            ],
            [
                'name' => 'Syria',
                'name_native' => 'سوريا',
                'phone_code' => '963',
                'code' => 'SY',
                'flag' => '🇸🇾',
            ],
            [
                'name' => 'Taiwan',
                'name_native' => '台灣',
                'phone_code' => '886',
                'code' => 'TW',
                'flag' => '🇹🇼',
            ],
            [
                'name' => 'Tajikistan',
                'name_native' => 'Тоҷикистон',
                'phone_code' => '992',
                'code' => 'TJ',
                'flag' => '🇹🇯',
            ],
            [
                'name' => 'Tanzania',
                'name_native' => 'Tanzania',
                'phone_code' => '255',
                'code' => 'TZ',
                'flag' => '🇹🇿',
            ],
            [
                'name' => 'Thailand',
                'name_native' => 'ประเทศไทย',
                'phone_code' => '66',
                'code' => 'TH',
                'flag' => '🇹🇭',
            ],
            [
                'name' => 'Togo',
                'name_native' => 'Togo',
                'phone_code' => '228',
                'code' => 'TG',
                'flag' => '🇹🇬',
            ],
            [
                'name' => 'Tonga',
                'name_native' => 'Tonga',
                'phone_code' => '676',
                'code' => 'TO',
                'flag' => '🇹🇴',
            ],
            [
                'name' => 'Trinidad and Tobago',
                'name_native' => 'Trinidad and Tobago',
                'phone_code' => '1-868',
                'code' => 'TT',
                'flag' => '🇹🇹',
            ],
            [
                'name' => 'Tunisia',
                'name_native' => 'تونس',
                'phone_code' => '216',
                'code' => 'TN',
                'flag' => '🇹🇳',
            ],
            [
                'name' => 'Turkey',
                'name_native' => 'Türkiye',
                'phone_code' => '90',
                'code' => 'TR',
                'flag' => '🇹🇷',
            ],
            [
                'name' => 'Turkmenistan',
                'name_native' => 'Türkmenistan',
                'phone_code' => '993',
                'code' => 'TM',
                'flag' => '🇹🇲',
            ],
            [
                'name' => 'Tuvalu',
                'name_native' => 'Tuvalu',
                'phone_code' => '688',
                'code' => 'TV',
                'flag' => '🇹🇻',
            ],
            [
                'name' => 'Uganda',
                'name_native' => 'Uganda',
                'phone_code' => '256',
                'code' => 'UG',
                'flag' => '🇺🇬',
            ],
            [
                'name' => 'Ukraine',
                'name_native' => 'Україна',
                'phone_code' => '380',
                'code' => 'UA',
                'flag' => '🇺🇦',
            ],
            [
                'name' => 'United Arab Emirates',
                'name_native' => 'الإمارات العربية المتحدة',
                'phone_code' => '971',
                'code' => 'AE',
                'flag' => '🇦🇪',
            ],
            [
                'name' => 'United Kingdom',
                'name_native' => 'United Kingdom',
                'phone_code' => '44',
                'code' => 'GB',
                'flag' => '🇬🇧',
            ],
            [
                'name' => 'United States',
                'name_native' => 'United States',
                'phone_code' => '1',
                'code' => 'US',
                'flag' => '🇺🇸',
            ],
            [
                'name' => 'Uruguay',
                'name_native' => 'Uruguay',
                'phone_code' => '598',
                'code' => 'UY',
                'flag' => '🇺🇾',
            ],
            [
                'name' => 'Uzbekistan',
                'name_native' => 'Oʻzbekiston',
                'phone_code' => '998',
                'code' => 'UZ',
                'flag' => '🇺🇿',
            ],
            [
                'name' => 'Vanuatu',
                'name_native' => 'Vanuatu',
                'phone_code' => '678',
                'code' => 'VU',
                'flag' => '🇻🇺',
            ],
            [
                'name' => 'Vatican City',
                'name_native' => 'Vaticano',
                'phone_code' => '379',
                'code' => 'VA',
                'flag' => '🇻🇦',
            ],
            [
                'name' => 'Venezuela',
                'name_native' => 'Venezuela',
                'phone_code' => '58',
                'code' => 'VE',
                'flag' => '🇻🇪',
            ],
            [
                'name' => 'Vietnam',
                'name_native' => 'Việt Nam',
                'phone_code' => '84',
                'code' => 'VN',
                'flag' => '🇻🇳',
            ],
            [
                'name' => 'Yemen',
                'name_native' => 'اليمن',
                'phone_code' => '967',
                'code' => 'YE',
                'flag' => '🇾🇪',
            ],
            [
                'name' => 'Zambia',
                'name_native' => 'Zambia',
                'phone_code' => '260',
                'code' => 'ZM',
                'flag' => '🇿🇲',
            ],
            [
                'name' => 'Zimbabwe',
                'name_native' => 'Zimbabwe',
                'phone_code' => '263',
                'code' => 'ZW',
                'flag' => '🇿🇼',
            ],


        ];
    }
}

